In [24]:
#pandas use for fatching file
import pandas as pd
data=pd.read_csv('C:\\Users\\shyam\\Desktop\\New folder\\nba.csv')
#print 5 rows default
#data.head()

#print 10 row 
#data.head(10)

#print all data
#print(data)
#data.head

In [42]:
#sorting of data
#row wise shorting axis=0
#inplace will true then it will reflect changes
data.sort_values(['Team','College'],axis=0,ascending=True,inplace=True)
data.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
316,Mike Muscala,Atlanta Hawks,31,PF,24,11-Jun,240,Bucknell,947276.0
314,Kyle Korver,Atlanta Hawks,26,SG,35,07-Jun,212,Creighton,5746479.0
312,Al Horford,Atlanta Hawks,15,C,30,10-Jun,245,Florida,12000000.0
311,Kirk Hinrich,Atlanta Hawks,12,SG,35,04-Jun,190,Kansas,2854940.0
315,Paul Millsap,Atlanta Hawks,4,PF,31,08-Jun,246,Louisiana Tech,18671659.0
310,Tim Hardaway Jr.,Atlanta Hawks,10,SG,24,06-Jun,205,Michigan,1304520.0
313,Kris Humphries,Atlanta Hawks,43,PF,31,09-Jun,235,Minnesota,1000000.0
309,Kent Bazemore,Atlanta Hawks,24,SF,26,05-Jun,201,Old Dominion,2000000.0
317,Lamar Patterson,Atlanta Hawks,13,SG,24,05-Jun,225,Pittsburgh,525093.0
319,Mike Scott,Atlanta Hawks,32,PF,27,08-Jun,237,Virginia,3333333.0

In [50]:
#scipy for mathamatical calculation
#numpy for matrics calculation
#matplotlib for graphical representation
#pandas for file fatching 
#sklearn for ML algorithm

#version of library
#python
import sys
print('python: {}'.format(sys.version))
#scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
#numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
#matplotlib
import matplotlib
print('matplot: {}'.format(matplotlib.__version__))
#pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
#scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

python: 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
scipy: 1.1.0
numpy: 1.15.4
matplot: 3.0.2
pandas: 0.23.4
sklearn: 0.20.1